#!/usr/bin/env python

import csv
import cx_Oracle as ora
import argparse
import time

def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('-c','--connection', dest='connection', required=True)
  parser.add_argument('-i','--infile', dest='infile', required=True)
  args = parser.parse_args()

  filename = 'output-hive-%s.csv' %(time.strftime("%Y%m%d-%H%M%S"))

  con = ora.connect(args.connection)
  cur = con.cursor()
  with open(args.infile, 'rb') as csvinfile:
    spamreader = csv.DictReader(csvinfile)
    for row in spamreader:
      result = cur.execute(row['query'])
      val = cur.fetchall()
      with open(filename, 'a') as csvoutfile:
        fieldnames = ['result']
        writer = csv.DictWriter(csvoutfile, fieldnames=fieldnames)
        writer.writerow({'result': row['query']})
        for result in val:
          print row['query']
          for item in result:
            writer.writerow({'result': item})
            print item
  cur.close()
  con.close()

main()
