#!/usr/bin/env python

import csv
import pyhs2
import argparse
import time
def main():

  parser = argparse.ArgumentParser()
  parser.add_argument('-i','--infile', dest='infile', required=True)
  parser.add_argument('-u','--user', dest='user', required=True)
  parser.add_argument('-p','--password', dest='password', required=True)
  parser.add_argument('-d','--database', dest='database', required=True)
  parser.add_argument('-v','--host', dest='host', required=True) 


  args = parser.parse_args()
  filename = 'output-hive-%s.csv' %(time.strftime("%Y%m%d-%H%M%S"))
  with open(args.infile, 'rb') as csvinfile:
    spamreader = csv.DictReader(csvinfile)
    for row in spamreader: 
      print row['query']   
      with pyhs2.connect(host=args.host, port=10000, authMechanism="PLAIN", user=args.user, password=args.password, database=args.database) as conn:
        with conn.cursor() as cur:
          with open(filename, 'a') as csvoutfile:
            fieldnames = ['result']
            writer = csv.DictWriter(csvoutfile, fieldnames=fieldnames)
            cur.execute(row['query'])
            for item in cur.fetch():
              writer.writerow({'result': row['query']})
              writer.writerow({'result': item})
              print item


main()
